Bump Confluent
navikt/isdialogmotekandidat pull request #60
Opened 2022-08-17 07:09 UTC by JMLindseth

Dette bør fikse en del snyk-issues.

2022-08-17 08:01 UTC, geir-waagboe commented
Vi må nok få en ny versjon av kafka-embedded-env før dette forsvinner helt. Har laget en PR i den app'en, så når det er merget kan vi oppgradere til 3.1.7.

2022-08-17 08:01 UTC, geir-waagboe approved these changes

2022-08-17 08:02 UTC, geir-waagboe commented on build.gradle.kts
> +    const val confluent = "7.2.1"
Tror kanskje Kafka bør oppgraderes til 3.2.0 med det samme for å holde ting konsistent.

2022-08-17 08:03 UTC, geir-waagboe requested changes
Tror kanskje Kafka bør oppgraderes til 3.2.0 med det samme for å holde ting konsistent.

2022-08-17 12:11 UTC, geir-waagboe approved these changes

2022-08-18 07:04 UTC, juneih approved these changes

2022-08-18 07:07 UTC, merged